version: '3.8'

services:
  db:
    build:
      context: ./data
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: RutinasDB
      MYSQL_USER: api_rutinas
      MYSQL_PASSWORD: mondongo
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - rutina-network

  api:
    build:
      context: ./api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://api_rutinas:mondongo@localhost/RutinasDB
      ROCKET_ADDRESS: 0.0.0.0
      ROCKET_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - rutina-network

networks:
  rutina-network:
    driver: bridge

volumes:
  db_data:
