name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Run JavaScript tests
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install JavaScript dependencies
        run: |
          cd test/javascript
          npm install
      - name: Run JavaScript tests
        run: |
          cd test/javascript
          npm test
      
      # Run Python tests
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Python dependencies
        run: |
          cd test/python
          pip install -r requirements.txt
      - name: Run Python tests
        run: |
          cd test/python
          python -m pytest

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push API image
        uses: docker/build-push-action@v4
        with:
          context: ./api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/rutina-api:latest
      
      - name: Build and push DB image
        uses: docker/build-push-action@v4
        with:
          context: ./data
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/rutina-db:latest