name: Rust CI/CD with Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  DOCKERHUB_USERNAME: "shinnog"
  DOCKERHUB_TOKEN: "dckr_pat_Q0WVCVgb_BMBboE4GsO6hu5kor0"

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build project
        run: cargo build --release
        working-directory: ./api

      - name: Run tests
        run: cargo test --verbose
        working-directory: ./api

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
          # Elimina los parámetros de ECR que causan el error
          # ecr: auto
          # logout: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./api
          file: ./api/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/rutina-app:latest
            ${{ env.DOCKERHUB_USERNAME }}/rutina-app:${{ github.sha }}
